<?php
$channelId = $block->getChannelId();
$scriptDisabled = $block->getScriptDisabled();
$isNew = 0;
$user = $block->getStore();
$user = json_encode($user);
$formAction = $block->getUrl("cleverpush/home/register");
$siteUrl = $block->getbaseUrl();
$cleverpushLogo = $block->getViewFileUrl('Cleverpush_WebPush::images/logo.png');
?>

<img src="<?php echo $block->escapeUrl($cleverpushLogo); ?>" class="cleverpush-logo">

<form method="post" action='<?php echo $block->escapeUrl($formAction); ?>'>
    <?php echo $block->getBlockHtml('formkey'); ?>

    <section class="admin__page-section">            
        <div class="admin__page-section-title head-account">
            <span class="title">Setup</span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__field field field-group_id">
                <label class="label admin__field-label"><span>CleverPush Channel ID</span></label>
                <div class="admin__field-control control">
                    <input type="text" name="channelId" id="channelId" value="<?php echo $channelId; ?>" class="admin__control-text" style="margin-bottom: 15px" placeholder="Channel ID…">
                </div>
            </div>
        </div>
    </section>

    <section class="admin__page-section">            
        <div class="admin__page-section-title head-account">
            <span class="title">Advanced</span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__field field field-group_id">
                <label class="label admin__field-label"><span>Disable CleverPush</span></label>

                <div class="admin__field admin__field-option">
                    <input type="checkbox" id="cleverpush-script_disabled" name="scriptDisabled" value="true" <?php echo $scriptDisabled ? 'checked' : '' ?> class="admin__control-checkbox">
                    <label for="cleverpush-script_disabled" class="admin__field-label">Disable CleverPush script</label>
                </div>
            </div>
        </div>
    </section>

    <button type="submit" class="action-default primary" name="tokensubmit" value="submit">Save</button>
</form> 

<script type="text/x-magento-init">
    {
        "*": {
            "CleverPush/js/admin": {
                "izUser": <?php /* @noEscape */ echo $user; ?>,
                "siteUrl": "<?php echo $block->escapeUrl($siteUrl); ?>"
            }
        }
    }
</script>
